server:
  port: 8081

#数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost/guijia?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
    username: root
    password: 415500wyh

#mybatis-plus配置
mybatis-plus:
 mapper-locations: classpath:/mapper/*Mapper.xml
#配置mybatis数据返回类型别名
 type-aliases-package: com.demo.pojo
 #日志
logging:
  level:
    com.demo.mapper: debug
jwt:
  # Jwt存储的请求头
  tokenHeader: Authorization
  # Jwt加密秘钥
  secret: yeb-secret
  # Jwt 的超期限时间（60*60）*24
  expiration: 604800
  # Jwt负载中拿到开头
  tokenHead: Bearer